artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: C:/Users/chris/Downloads/cassava-disease.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  train_dir: artifacts/data_ingestion/train.zip
  test_dir: artifacts/data_ingestion/test.zip